/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import Kelas.Bagian;
import Kelas.Kategori;
import Kelas.SuratKeluar;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rizan
 */
public class MenuDashboard extends javax.swing.JPanel {

    /**
     * Creates new form MenuDashboard
     */
    public MenuDashboard() {
        initComponents();
        tampilJumlahKategoriSurat();
        tampilJumlahBagianSurat();
        tampilJumlahSuratKeluar();
    }

    void tampilJumlahKategoriSurat() {
        try {
            Kategori jumKategori = new Kategori();
            int jumlahKode = jumKategori.TampilJumlahKategori();

            lb_Kategori.setText(String.valueOf(jumlahKode));
        } catch (SQLException ex) {
            Logger.getLogger(MenuDashboard.class.getName()).log(Level.SEVERE, null, ex);
            lb_Kategori.setText("Error");
        }
    }

    void tampilJumlahBagianSurat() {
        try {
            Bagian jumBagian = new Bagian();
            int jumlahKode = jumBagian.TampilJumlahBagian();

            lb_Bagian.setText(String.valueOf(jumlahKode));
        } catch (SQLException ex) {
            Logger.getLogger(MenuDashboard.class.getName()).log(Level.SEVERE, null, ex);
            lb_Bagian.setText("Error");
        }
    }

    void tampilJumlahSuratKeluar() {
        try {
            SuratKeluar jumSuKel = new SuratKeluar();
            int jumlahKode = jumSuKel.TampilJumlahBagian();

            lb_SuratKeluar.setText(String.valueOf(jumlahKode));
        } catch (SQLException ex) {
            Logger.getLogger(MenuDashboard.class.getName()).log(Level.SEVERE, null, ex);
            lb_SuratKeluar.setText("Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_Kategori = new javax.swing.JLabel();
        lb_Bagian = new javax.swing.JLabel();
        lb_SuratMasuk = new javax.swing.JLabel();
        lb_SuratKeluar = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        pn_Main.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel1.setText("Menu Dashboard");

        lb_Kategori.setFont(new java.awt.Font("MS UI Gothic", 1, 48)); // NOI18N
        lb_Kategori.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Kategori.setText("999");
        lb_Kategori.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jumlah Kategori", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Palatino Linotype", 0, 18))); // NOI18N

        lb_Bagian.setFont(new java.awt.Font("MS UI Gothic", 1, 48)); // NOI18N
        lb_Bagian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Bagian.setText("999");
        lb_Bagian.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jumlah Bagian", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Palatino Linotype", 0, 18))); // NOI18N

        lb_SuratMasuk.setFont(new java.awt.Font("MS UI Gothic", 1, 48)); // NOI18N
        lb_SuratMasuk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_SuratMasuk.setText("999");
        lb_SuratMasuk.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jumlah Surat Masuk", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Palatino Linotype", 0, 18))); // NOI18N

        lb_SuratKeluar.setFont(new java.awt.Font("MS UI Gothic", 1, 48)); // NOI18N
        lb_SuratKeluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_SuratKeluar.setText("999");
        lb_SuratKeluar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jumlah Surat Keluar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Palatino Linotype", 0, 18))); // NOI18N

        javax.swing.GroupLayout pn_MainLayout = new javax.swing.GroupLayout(pn_Main);
        pn_Main.setLayout(pn_MainLayout);
        pn_MainLayout.setHorizontalGroup(
            pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pn_MainLayout.createSequentialGroup()
                        .addComponent(lb_Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_Bagian, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_SuratMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_SuratKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        pn_MainLayout.setVerticalGroup(
            pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Bagian, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_SuratMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_SuratKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(450, Short.MAX_VALUE))
        );

        add(pn_Main, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_Bagian;
    private javax.swing.JLabel lb_Kategori;
    private javax.swing.JLabel lb_SuratKeluar;
    private javax.swing.JLabel lb_SuratMasuk;
    private javax.swing.JPanel pn_Main;
    // End of variables declaration//GEN-END:variables
}
